#!/bin/bash

if [ -n "$NEW_UID" -a "$NEW_UID" != "$(id -u civpb)" ] ; then

NEW_UID=${1:-$NEW_UID}
NEW_GID=${2:-$NEW_GID}

if [ 1000 -gt "$NEW_UID" -o 1000 -gt "$NEW_GID" ] ; then
    echo "Hey, input no numbers or too low."
    exit -1
fi

usermod -u "$NEW_UID" civpb
groupmod -g "$NEW_GID" civpb

# Adapt home dir of user
chown -P -R "$NEW_UID:$NEW_GID" /home/civpb

# NOT recursive
chown "$NEW_UID:$NEW_GID"  /app /altroot /altroot/PBs

fi
