#!/bin/bash

if [ "$USER" = "civpb" ] ; then
	# Starting by supervisord
	cd /home/civpb
	#script /dev/null
	screen -c .screenrc
	# Hm, does not work...
else
	# Starting by ENTRYPOINT or shell
	su -c "cd /home/civpb && screen -c .screenrc" civpb
fi
